services:
  triton:
    image: nvcr.io/nvidia/tritonserver:26.08-py3

    ports:
      - 8000:8000
      - 8001:8001
      - 8002:8002

    volumes:
      - ./serving/model_repository:/models

    command: 
      - tritonserver
      - --model-repository=/models
      #en produccion se usa
      - --model-control-mode=explicit

      #- --model-control-mode=poll
      #- --repository-poll-secs=15




#docker compose up
    
    

