services:
  triton:
    image: nvcr.io/nvidia/tritonserver:26.08-py3

    ports:
      - 8000:8000
      - 8001:8001
      - 8002:8002

    volumes:
      - ../serving/model_repository:/models

    command:
      - /bin/sh
      - -c
      - |
        if [ ! -f /models/vgg11/1/model.onnx ]; then
          echo "Falta /models/vgg11/1/model.onnx. Ejecuta: python serving/export_con_onnx.py";
          exit 1;
        fi
        exec tritonserver --model-repository=/models

# docker compose -f utils/docker-compose.yml up
